# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatbot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chatbot.proto',
  package='chatbot',
  syntax='proto3',
  serialized_options=_b('\n\007serviceB\007ChatBotP\001'),
  serialized_pb=_b('\n\rchatbot.proto\x12\x07\x63hatbot\"!\n\x03\x42ot\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x10\n\x0eListBotRequest\"-\n\x0fListBotResponse\x12\x1a\n\x04\x62ots\x18\x01 \x03(\x0b\x32\x0c.chatbot.Bot\"!\n\rChatBotConfig\x12\x10\n\x08\x62ot_code\x18\x01 \x01(\t\"[\n\x0e\x43hatBotRequest\x12.\n\x0e\x63hatbot_config\x18\x01 \x01(\x0b\x32\x16.chatbot.ChatBotConfig\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x08\"M\n\x0f\x43hatBotResponse\x12\x1f\n\x06status\x18\x01 \x01(\x0b\x32\x0f.chatbot.Status\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x08\"\'\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8b\x01\n\x07\x43hatBot\x12<\n\x07ListBot\x12\x17.chatbot.ListBotRequest\x1a\x18.chatbot.ListBotResponse\x12\x42\n\tChatToBot\x12\x17.chatbot.ChatBotRequest\x1a\x18.chatbot.ChatBotResponse(\x01\x30\x01\x42\x14\n\x07serviceB\x07\x43hatBotP\x01\x62\x06proto3')
)




_BOT = _descriptor.Descriptor(
  name='Bot',
  full_name='chatbot.Bot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='chatbot.Bot.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='chatbot.Bot.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=59,
)


_LISTBOTREQUEST = _descriptor.Descriptor(
  name='ListBotRequest',
  full_name='chatbot.ListBotRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=77,
)


_LISTBOTRESPONSE = _descriptor.Descriptor(
  name='ListBotResponse',
  full_name='chatbot.ListBotResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bots', full_name='chatbot.ListBotResponse.bots', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=124,
)


_CHATBOTCONFIG = _descriptor.Descriptor(
  name='ChatBotConfig',
  full_name='chatbot.ChatBotConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bot_code', full_name='chatbot.ChatBotConfig.bot_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=159,
)


_CHATBOTREQUEST = _descriptor.Descriptor(
  name='ChatBotRequest',
  full_name='chatbot.ChatBotRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chatbot_config', full_name='chatbot.ChatBotRequest.chatbot_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='chatbot.ChatBotRequest.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='chatbot.ChatBotRequest.end', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=252,
)


_CHATBOTRESPONSE = _descriptor.Descriptor(
  name='ChatBotResponse',
  full_name='chatbot.ChatBotResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='chatbot.ChatBotResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='chatbot.ChatBotResponse.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='chatbot.ChatBotResponse.end', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=331,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='chatbot.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='chatbot.Status.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='chatbot.Status.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=372,
)

_LISTBOTRESPONSE.fields_by_name['bots'].message_type = _BOT
_CHATBOTREQUEST.fields_by_name['chatbot_config'].message_type = _CHATBOTCONFIG
_CHATBOTRESPONSE.fields_by_name['status'].message_type = _STATUS
DESCRIPTOR.message_types_by_name['Bot'] = _BOT
DESCRIPTOR.message_types_by_name['ListBotRequest'] = _LISTBOTREQUEST
DESCRIPTOR.message_types_by_name['ListBotResponse'] = _LISTBOTRESPONSE
DESCRIPTOR.message_types_by_name['ChatBotConfig'] = _CHATBOTCONFIG
DESCRIPTOR.message_types_by_name['ChatBotRequest'] = _CHATBOTREQUEST
DESCRIPTOR.message_types_by_name['ChatBotResponse'] = _CHATBOTRESPONSE
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Bot = _reflection.GeneratedProtocolMessageType('Bot', (_message.Message,), {
  'DESCRIPTOR' : _BOT,
  '__module__' : 'chatbot_pb2'
  # @@protoc_insertion_point(class_scope:chatbot.Bot)
  })
_sym_db.RegisterMessage(Bot)

ListBotRequest = _reflection.GeneratedProtocolMessageType('ListBotRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTBOTREQUEST,
  '__module__' : 'chatbot_pb2'
  # @@protoc_insertion_point(class_scope:chatbot.ListBotRequest)
  })
_sym_db.RegisterMessage(ListBotRequest)

ListBotResponse = _reflection.GeneratedProtocolMessageType('ListBotResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTBOTRESPONSE,
  '__module__' : 'chatbot_pb2'
  # @@protoc_insertion_point(class_scope:chatbot.ListBotResponse)
  })
_sym_db.RegisterMessage(ListBotResponse)

ChatBotConfig = _reflection.GeneratedProtocolMessageType('ChatBotConfig', (_message.Message,), {
  'DESCRIPTOR' : _CHATBOTCONFIG,
  '__module__' : 'chatbot_pb2'
  # @@protoc_insertion_point(class_scope:chatbot.ChatBotConfig)
  })
_sym_db.RegisterMessage(ChatBotConfig)

ChatBotRequest = _reflection.GeneratedProtocolMessageType('ChatBotRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHATBOTREQUEST,
  '__module__' : 'chatbot_pb2'
  # @@protoc_insertion_point(class_scope:chatbot.ChatBotRequest)
  })
_sym_db.RegisterMessage(ChatBotRequest)

ChatBotResponse = _reflection.GeneratedProtocolMessageType('ChatBotResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHATBOTRESPONSE,
  '__module__' : 'chatbot_pb2'
  # @@protoc_insertion_point(class_scope:chatbot.ChatBotResponse)
  })
_sym_db.RegisterMessage(ChatBotResponse)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'chatbot_pb2'
  # @@protoc_insertion_point(class_scope:chatbot.Status)
  })
_sym_db.RegisterMessage(Status)


DESCRIPTOR._options = None

_CHATBOT = _descriptor.ServiceDescriptor(
  name='ChatBot',
  full_name='chatbot.ChatBot',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=375,
  serialized_end=514,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListBot',
    full_name='chatbot.ChatBot.ListBot',
    index=0,
    containing_service=None,
    input_type=_LISTBOTREQUEST,
    output_type=_LISTBOTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ChatToBot',
    full_name='chatbot.ChatBot.ChatToBot',
    index=1,
    containing_service=None,
    input_type=_CHATBOTREQUEST,
    output_type=_CHATBOTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATBOT)

DESCRIPTOR.services_by_name['ChatBot'] = _CHATBOT

# @@protoc_insertion_point(module_scope)
