# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streaming_voice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='streaming_voice.proto',
  package='streaming_voice',
  syntax='proto3',
  serialized_options=_b('\n\007serviceB\016StreamingVoiceP\001'),
  serialized_pb=_b('\n\x15streaming_voice.proto\x12\x0fstreaming_voice\"!\n\x0cVoiceRequest\x12\x11\n\tbyte_buff\x18\x01 \x01(\x0c\"\xc2\x03\n\tTextReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x08 \x01(\t\x12\x0f\n\x07segment\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\t\x12\x31\n\x06result\x18\x04 \x01(\x0b\x32!.streaming_voice.TextReply.Result\x12\x15\n\rsegment_start\x18\x05 \x01(\x02\x12\x16\n\x0esegment_length\x18\x06 \x01(\x02\x12\x14\n\x0ctotal_length\x18\x07 \x01(\x02\x1a\x82\x02\n\x06Result\x12?\n\nhypotheses\x18\x01 \x03(\x0b\x32+.streaming_voice.TextReply.Result.Hypothese\x12\r\n\x05\x66inal\x18\x02 \x01(\x08\x1a\xa7\x01\n\tHypothese\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x19\n\x11transcript_normed\x18\x02 \x01(\t\x12\x1d\n\x15transcript_urlencoded\x18\x03 \x01(\t\x12$\n\x1ctranscript_normed_urlencoded\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x12\n\nlikelihood\x18\x06 \x01(\x02\x32[\n\x0bStreamVoice\x12L\n\tSendVoice\x12\x1d.streaming_voice.VoiceRequest\x1a\x1a.streaming_voice.TextReply\"\x00(\x01\x30\x01\x42\x1b\n\x07serviceB\x0eStreamingVoiceP\x01\x62\x06proto3')
)




_VOICEREQUEST = _descriptor.Descriptor(
  name='VoiceRequest',
  full_name='streaming_voice.VoiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='byte_buff', full_name='streaming_voice.VoiceRequest.byte_buff', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=75,
)


_TEXTREPLY_RESULT_HYPOTHESE = _descriptor.Descriptor(
  name='Hypothese',
  full_name='streaming_voice.TextReply.Result.Hypothese',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transcript', full_name='streaming_voice.TextReply.Result.Hypothese.transcript', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transcript_normed', full_name='streaming_voice.TextReply.Result.Hypothese.transcript_normed', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transcript_urlencoded', full_name='streaming_voice.TextReply.Result.Hypothese.transcript_urlencoded', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transcript_normed_urlencoded', full_name='streaming_voice.TextReply.Result.Hypothese.transcript_normed_urlencoded', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='streaming_voice.TextReply.Result.Hypothese.confidence', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='likelihood', full_name='streaming_voice.TextReply.Result.Hypothese.likelihood', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=528,
)

_TEXTREPLY_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='streaming_voice.TextReply.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hypotheses', full_name='streaming_voice.TextReply.Result.hypotheses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='final', full_name='streaming_voice.TextReply.Result.final', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TEXTREPLY_RESULT_HYPOTHESE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=528,
)

_TEXTREPLY = _descriptor.Descriptor(
  name='TextReply',
  full_name='streaming_voice.TextReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='streaming_voice.TextReply.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='streaming_voice.TextReply.msg', index=1,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='segment', full_name='streaming_voice.TextReply.segment', index=2,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='streaming_voice.TextReply.id', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='streaming_voice.TextReply.result', index=4,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='segment_start', full_name='streaming_voice.TextReply.segment_start', index=5,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='segment_length', full_name='streaming_voice.TextReply.segment_length', index=6,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_length', full_name='streaming_voice.TextReply.total_length', index=7,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TEXTREPLY_RESULT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=528,
)

_TEXTREPLY_RESULT_HYPOTHESE.containing_type = _TEXTREPLY_RESULT
_TEXTREPLY_RESULT.fields_by_name['hypotheses'].message_type = _TEXTREPLY_RESULT_HYPOTHESE
_TEXTREPLY_RESULT.containing_type = _TEXTREPLY
_TEXTREPLY.fields_by_name['result'].message_type = _TEXTREPLY_RESULT
DESCRIPTOR.message_types_by_name['VoiceRequest'] = _VOICEREQUEST
DESCRIPTOR.message_types_by_name['TextReply'] = _TEXTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VoiceRequest = _reflection.GeneratedProtocolMessageType('VoiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _VOICEREQUEST,
  '__module__' : 'streaming_voice_pb2'
  # @@protoc_insertion_point(class_scope:streaming_voice.VoiceRequest)
  })
_sym_db.RegisterMessage(VoiceRequest)

TextReply = _reflection.GeneratedProtocolMessageType('TextReply', (_message.Message,), {

  'Result' : _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {

    'Hypothese' : _reflection.GeneratedProtocolMessageType('Hypothese', (_message.Message,), {
      'DESCRIPTOR' : _TEXTREPLY_RESULT_HYPOTHESE,
      '__module__' : 'streaming_voice_pb2'
      # @@protoc_insertion_point(class_scope:streaming_voice.TextReply.Result.Hypothese)
      })
    ,
    'DESCRIPTOR' : _TEXTREPLY_RESULT,
    '__module__' : 'streaming_voice_pb2'
    # @@protoc_insertion_point(class_scope:streaming_voice.TextReply.Result)
    })
  ,
  'DESCRIPTOR' : _TEXTREPLY,
  '__module__' : 'streaming_voice_pb2'
  # @@protoc_insertion_point(class_scope:streaming_voice.TextReply)
  })
_sym_db.RegisterMessage(TextReply)
_sym_db.RegisterMessage(TextReply.Result)
_sym_db.RegisterMessage(TextReply.Result.Hypothese)


DESCRIPTOR._options = None

_STREAMVOICE = _descriptor.ServiceDescriptor(
  name='StreamVoice',
  full_name='streaming_voice.StreamVoice',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=530,
  serialized_end=621,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendVoice',
    full_name='streaming_voice.StreamVoice.SendVoice',
    index=0,
    containing_service=None,
    input_type=_VOICEREQUEST,
    output_type=_TEXTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STREAMVOICE)

DESCRIPTOR.services_by_name['StreamVoice'] = _STREAMVOICE

# @@protoc_insertion_point(module_scope)
