# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voicebot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='voicebot.proto',
  package='voicebot',
  syntax='proto3',
  serialized_options=_b('\n\007serviceB\017VoiceBotServiceP\001'),
  serialized_pb=_b('\n\x0evoicebot.proto\x12\x08voicebot\"(\n\nCallCenter\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x17\n\x15ListCallCenterRequest\"D\n\x16ListCallCenterResponse\x12*\n\x0c\x63\x61ll_centers\x18\x01 \x03(\x0b\x32\x14.voicebot.CallCenter\";\n\x0eVoiceBotConfig\x12\x18\n\x10\x63\x61ll_center_code\x18\x01 \x01(\t\x12\x0f\n\x07is_male\x18\x02 \x01(\x08\"[\n\x0fVoiceBotRequest\x12\x31\n\x0fvoicebot_config\x18\x01 \x01(\x0b\x32\x18.voicebot.VoiceBotConfig\x12\x15\n\raudio_content\x18\x02 \x01(\x0c\"v\n\x10VoiceBotResponse\x12 \n\x06status\x18\x01 \x01(\x0b\x32\x10.voicebot.Status\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x11\n\taudio_url\x18\x03 \x01(\t\x12\x10\n\x08text_asr\x18\x04 \x01(\t\x12\r\n\x05\x66inal\x18\x05 \x01(\x08\"\'\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa7\x01\n\x08VoiceBot\x12S\n\x0eListCallCenter\x12\x1f.voicebot.ListCallCenterRequest\x1a .voicebot.ListCallCenterResponse\x12\x46\n\tCallToBot\x12\x19.voicebot.VoiceBotRequest\x1a\x1a.voicebot.VoiceBotResponse(\x01\x30\x01\x42\x1c\n\x07serviceB\x0fVoiceBotServiceP\x01\x62\x06proto3')
)




_CALLCENTER = _descriptor.Descriptor(
  name='CallCenter',
  full_name='voicebot.CallCenter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='voicebot.CallCenter.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='voicebot.CallCenter.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=68,
)


_LISTCALLCENTERREQUEST = _descriptor.Descriptor(
  name='ListCallCenterRequest',
  full_name='voicebot.ListCallCenterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=93,
)


_LISTCALLCENTERRESPONSE = _descriptor.Descriptor(
  name='ListCallCenterResponse',
  full_name='voicebot.ListCallCenterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='call_centers', full_name='voicebot.ListCallCenterResponse.call_centers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=163,
)


_VOICEBOTCONFIG = _descriptor.Descriptor(
  name='VoiceBotConfig',
  full_name='voicebot.VoiceBotConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='call_center_code', full_name='voicebot.VoiceBotConfig.call_center_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_male', full_name='voicebot.VoiceBotConfig.is_male', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=224,
)


_VOICEBOTREQUEST = _descriptor.Descriptor(
  name='VoiceBotRequest',
  full_name='voicebot.VoiceBotRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='voicebot_config', full_name='voicebot.VoiceBotRequest.voicebot_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio_content', full_name='voicebot.VoiceBotRequest.audio_content', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=317,
)


_VOICEBOTRESPONSE = _descriptor.Descriptor(
  name='VoiceBotResponse',
  full_name='voicebot.VoiceBotResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='voicebot.VoiceBotResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='voicebot.VoiceBotResponse.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio_url', full_name='voicebot.VoiceBotResponse.audio_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text_asr', full_name='voicebot.VoiceBotResponse.text_asr', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='final', full_name='voicebot.VoiceBotResponse.final', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=437,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='voicebot.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='voicebot.Status.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='voicebot.Status.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=478,
)

_LISTCALLCENTERRESPONSE.fields_by_name['call_centers'].message_type = _CALLCENTER
_VOICEBOTREQUEST.fields_by_name['voicebot_config'].message_type = _VOICEBOTCONFIG
_VOICEBOTRESPONSE.fields_by_name['status'].message_type = _STATUS
DESCRIPTOR.message_types_by_name['CallCenter'] = _CALLCENTER
DESCRIPTOR.message_types_by_name['ListCallCenterRequest'] = _LISTCALLCENTERREQUEST
DESCRIPTOR.message_types_by_name['ListCallCenterResponse'] = _LISTCALLCENTERRESPONSE
DESCRIPTOR.message_types_by_name['VoiceBotConfig'] = _VOICEBOTCONFIG
DESCRIPTOR.message_types_by_name['VoiceBotRequest'] = _VOICEBOTREQUEST
DESCRIPTOR.message_types_by_name['VoiceBotResponse'] = _VOICEBOTRESPONSE
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CallCenter = _reflection.GeneratedProtocolMessageType('CallCenter', (_message.Message,), {
  'DESCRIPTOR' : _CALLCENTER,
  '__module__' : 'voicebot_pb2'
  # @@protoc_insertion_point(class_scope:voicebot.CallCenter)
  })
_sym_db.RegisterMessage(CallCenter)

ListCallCenterRequest = _reflection.GeneratedProtocolMessageType('ListCallCenterRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTCALLCENTERREQUEST,
  '__module__' : 'voicebot_pb2'
  # @@protoc_insertion_point(class_scope:voicebot.ListCallCenterRequest)
  })
_sym_db.RegisterMessage(ListCallCenterRequest)

ListCallCenterResponse = _reflection.GeneratedProtocolMessageType('ListCallCenterResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTCALLCENTERRESPONSE,
  '__module__' : 'voicebot_pb2'
  # @@protoc_insertion_point(class_scope:voicebot.ListCallCenterResponse)
  })
_sym_db.RegisterMessage(ListCallCenterResponse)

VoiceBotConfig = _reflection.GeneratedProtocolMessageType('VoiceBotConfig', (_message.Message,), {
  'DESCRIPTOR' : _VOICEBOTCONFIG,
  '__module__' : 'voicebot_pb2'
  # @@protoc_insertion_point(class_scope:voicebot.VoiceBotConfig)
  })
_sym_db.RegisterMessage(VoiceBotConfig)

VoiceBotRequest = _reflection.GeneratedProtocolMessageType('VoiceBotRequest', (_message.Message,), {
  'DESCRIPTOR' : _VOICEBOTREQUEST,
  '__module__' : 'voicebot_pb2'
  # @@protoc_insertion_point(class_scope:voicebot.VoiceBotRequest)
  })
_sym_db.RegisterMessage(VoiceBotRequest)

VoiceBotResponse = _reflection.GeneratedProtocolMessageType('VoiceBotResponse', (_message.Message,), {
  'DESCRIPTOR' : _VOICEBOTRESPONSE,
  '__module__' : 'voicebot_pb2'
  # @@protoc_insertion_point(class_scope:voicebot.VoiceBotResponse)
  })
_sym_db.RegisterMessage(VoiceBotResponse)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'voicebot_pb2'
  # @@protoc_insertion_point(class_scope:voicebot.Status)
  })
_sym_db.RegisterMessage(Status)


DESCRIPTOR._options = None

_VOICEBOT = _descriptor.ServiceDescriptor(
  name='VoiceBot',
  full_name='voicebot.VoiceBot',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=481,
  serialized_end=648,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListCallCenter',
    full_name='voicebot.VoiceBot.ListCallCenter',
    index=0,
    containing_service=None,
    input_type=_LISTCALLCENTERREQUEST,
    output_type=_LISTCALLCENTERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CallToBot',
    full_name='voicebot.VoiceBot.CallToBot',
    index=1,
    containing_service=None,
    input_type=_VOICEBOTREQUEST,
    output_type=_VOICEBOTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VOICEBOT)

DESCRIPTOR.services_by_name['VoiceBot'] = _VOICEBOT

# @@protoc_insertion_point(module_scope)
