FINISH_CONVERSATION = "_END_"
STOP_CONVERSATION_SENTENCE = ["Stop", "Shut up"]
SCRIPT_FILE = "./chatbot/resources/Duoc_callout.json"
# SCRIPT_FILE = "./chatbot/resources/Duoc_callin.json"
UNKNOWN = "Tôi không hiểu, bạn vui lòng nói lại"
ERROR_INPUT = "Thông tin bạn đưa ra không hợp lệ, mời bạn đọc lại"
ERROR_CHOOSE = "Anh nhắc lại lựa chọn với, em không rõ"
USER_INFO = "./chatbot/resources/user_info"
SESSION_LIVE_TIME = 60.00
QA_FILE = "./chatbot/resources/qa.json"
QA_KEYWORD = "./chatbot/resources/qa_keyword.json"
MEDICINE_NAME = "./chatbot/resources/medicine_name.json"